### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by barryvdh** [ngmy/webloyer#63]
Hey!

I was going to create my own web UI for Deployer (or Rocketeer), and while researching some bugs I find your package, which takes a very similar approach (obviously Laravel, calling the phar, but also queues, because of the Forward Agent etc., ansi to html etc)

I'm not really sure if I want to go the the trouble of creating my own version, so was interested in what your roadmap is, if you have anything planned. What I'm thinking of is:
- Javascript events, (Laravel echo?) to notify the UI of changes, auto-update the output
- Configure verbosity levels etc.
- More notifications (Slack?) using the 5.3 notifications.
- Webhook support (Github post commit hook to trigger deployments automatically?)

And what I'm currently find a bit odd is the structure. I'm guessing because you just use it differently than me :) In my case, I usually have a lot of small projects, each their own user and a few different servers. So each server config is mostly just used once or twice, so I would more expect this to be inside of the Project itself, no need to seperate it (or at least be able to create a new server while creating a project).
Also, I usually have staging and production, which use the exact same git repo and recipe, only different environment (path or server), so would make more sense to have Projects have the base settings, and inside a project define environments that override settings. And then just choose, deploy on (dropdown->staging/production).

I'm curious of your thoughts :)

**Comment by sigismund** [comment]
It seems that ngmy is quite busy.
Barryvdh, if you change your mind and start your own project, I would be glad to help you in any way I can.

**Comment by ngmy** [comment]
Hi,

This project is for users (including me) and for my Laravel learning too.
I do not have a clear roadmap because I implement necessary features and interesting features as appropriate.

> - Javascript events, (Laravel echo?) to notify the UI of changes, auto-update the output

I am interested in Laravel Echo and want to implement it, but It will not happen soon.
Because I do not have time to upgrade to Laravel 5.3.

> - Configure verbosity levels etc.

I plan to implement it.

> - More notifications (Slack?) using the 5.3 notifications.

I will probably implement it, but It will not happen soon.
Because it can be realized with just a Deployer's recipe file.

> - Webhook support (Github post commit hook to trigger deployments automatically?)

I have already implemented it.

I adopt the current structure for the following reasons:

* I do not want to prescribe how to use users
* I want to be able to reuse and combine Deployer's recipe files or server files as a component
